title: 鴻鷹
email: liu.hongying@hotmail.com
description: >
  良い未来のため、頑張っています。
baseurl: ""
url: "https://www.gekal.cn"
twitter_username: GekalCn
github_username:  gekal

lang: ja

# disqus config
disqus:
  shortname: 'gekalcn'

# google analytics
google_analytics: UA-132360060-1

# google advertisements
google_advertisements: ca-pub-7697967482848510
google_advertisements_slot: 8123451

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
theme: minima
minima:
  date_format: "%Y/%m/%d"
plugins:
  - jekyll-feed

include: [pages]
