title: 鸿鹰部落
email: liu.hongying@hotmail.com
description: >
  留鸿鹰一片天，志男儿四方心。
baseurl: ""
url: "https://gekal.cn"
twitter_username: KoeiRyu
github_username:  gekal

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include: [pages]
