title: 鴻鷹
email: liu.hongying@hotmail.com
description: >
  良い未来のため、頑張っています。
author: gekal
baseurl: ""
url: "https://gekal-study-jekyll.github.io/"

# Social Profiles
twitter_username: GekalCn
github_username: gekal
# facebook_username: GekalCn
# instagram_username: gekalcn
linkedin_username: gekal

# disqus config
disqus:
  shortname: 'gekalcn'

# google analytics
google_analytics:   UA-132360060-1

# google advertisements
google_advertisements: ca-pub-7697967482848510
google_advertisements_slot: 8123451

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
