title: 鴻鷹
email: liu.hongying@hotmail.com
description: >
  良い未来のため、頑張っています。
baseurl: ""
url: "https://gekal.cn"
twitter_username: KoeiRyu
github_username:  gekal

# disqus config
disqus:
  shortname: 'gekalcn'

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
theme: minima
minima:
  date_format: "%Y/%m/%d"
plugins:
  - jekyll-feed

include: [pages]
