version: "3.1"

services:
  jekyll:
    container_name: jekyll-gekalcn
    image: jekyll/jekyll:stable
    ports:
      - 4000:4000
    command: jekyll serve
    restart: always
    volumes:
      - ${VOLUMES_BASE:-.}:/srv/jekyll
      - ${VOLUMES_BASE:-.}/vendor/bundle:/usr/local/bundle
